### ISSUE TITLE
MA VERAMENTE ????

### ISSUE THREAD

**Issue by TonySchiano** [nicoDs96/unicolk#2]
Tutti possono avere accesso con una semplice ricerca a 30000 email, sei veramente un genio....
Stai condividendo 30k email su github, posso capire che vuoi offrire un servizio per aiutare gli utenti colpiti ma almeno fallo decentemenete e non peggiorare il problema.
https://raw.githubusercontent.com/nicoDs96/unicolk/master/mail.txt

**Comment by TonySchiano** [comment]
correzione 166k email

**Comment by nicoDs96** [comment]
Ciao tony, ti ringrazio per il suggerimento, un po'meno per i toni. Il sito è solo una pronta risposta per cercare di far cessare l'inoltro del file con le email e password in chiaro su WhatsApp. É stato partorito in 30 min. Ad ogni modo le tue critiche sono leggittime, oggi ho avuto modo di lavorarci per bene. 
Ciao e grazie

**Comment by TonySchiano** [comment]
https://raw.githubusercontent.com/nicoDs96/unicolk/d2e13cbee0f8d653918403799c29b0b7dce21bd5/mail.txt si può ancora accedere al file con tutte le email. Ti ringrazione per averci messo una pezza momentanea cerca di eliminare tutta la history di github e rifai il commit dell'ultima versione. Oppure segui questa guida per rimuovere la storia di un file https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

Ciao e grazie
